### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by yuynagforhacker** [chriskaliX/drdos-framework#2]
并发attack时出现map资源竞争
golang版本：go version go1.15.7
运行环境：kali

**Comment by yuynagforhacker** [comment]
补充：-type mem时会出现此问题，-type dns无问题

**Comment by chriskaliX** [comment]
好的，俺去看看

**Comment by chriskaliX** [comment]
map忘记加锁了。目前没有测试环境了，用了sync包，大哥可以测试一下看看行不行~

**Comment by yuynagforhacker** [comment]
逻辑上没问题了，多谢老哥，没有响应应该是我list的问题

**Comment by chriskaliX** [comment]
好的，感谢指出错误~

**Comment by yuynagforhacker** [comment]
@chriskaliX 程序成功运行了，但是我对payload有些问题，如果可以的话能联系到您不？临时邮箱：TVRCMFpYTjBNVEF4UUhCeWIzUnZibTFoYVd3dVkyOXQ=
2次

**Comment by chriskaliX** [comment]
> @chriskaliX 程序成功运行了，但是我对payload有些问题，如果可以的话能联系到您不？临时邮箱：TVRCMFpYTjBNVEF4UUhCeWIzUnZibTFoYVd3dVkyOXQ=
> 
> 2次

已发送
