### ISSUE TITLE
阿里云的机器就可以吗不需要伪造ip吗

### ISSUE THREAD

**Issue by tqrj** [chriskaliX/drdos-framework#6]
不是太了解请教一下

**Comment by chriskaliX** [comment]
时间有点长，有点忘记了。只是check模式时候指定-s 指定内网吧，云上只测试过 check 模式

**Comment by tqrj** [comment]
应该得伪造ip才会有效果吧 不然发出去的包会被nat 转换成本机的ip了 达不到效果吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chriskaliX/drdos-framework] 阿里云的机器就可以吗不需要伪造ip吗 (Issue #6)





 
时间有点长，有点忘记了。只是check模式时候指定-s 指定内网吧，云上只测试过 check 模式
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chriskaliX** [comment]
云上我记得不一样，指定 -s 为公网 ip 好像会被 drop，你可以测一下

**Comment by tqrj** [comment]
ok好的感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月8日(星期一) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chriskaliX/drdos-framework] 阿里云的机器就可以吗不需要伪造ip吗 (Issue #6)





 
云上我记得不一样，指定 -s 为公网 ip 好像会被 drop，你可以测一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chriskaliX** [comment]
;-)
